GET http://localhost:5000/api/cities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImEiLCJpYXQiOjE1OTYyMTY2MjksImV4cCI6MTU5NjIxNzUyOX0.-czGuhV-qZ7ye_HyohIsvWJujRzsBjHZ3UtOvAhIpyU

###

GET http://localhost:5000/api/users/

###

GET http://localhost:5000/api/users/user/5f21ffe610b2c41dd412e787


###

GET http://localhost:5000/api/users/user/pfp/5f24655f06f31414643dcf7e